apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: dictionary
  name: dictionary
spec:
  replicas: 1
  selector:
    matchLabels:
      run: dictionary
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: dictionary
    spec:
      containers:
        - image: danielvaughan/word-game-tools-dictionary:latest
          imagePullPolicy: Always
          name: dictionary
          ports:
            - containerPort: 8080
              protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
