apiVersion: v1
kind: Service
metadata:
  labels:
    run: dictionary
  name: dictionary
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    run: dictionary
  type: LoadBalancer
